### ISSUE TITLE
Error on Shadowland Beta: Briefly displays errors on load

### ISSUE THREAD

**Issue by mightykong** [funkydude/BasicBuffs#1]
![BasicBuffsError](https://user-images.githubusercontent.com/4417339/92963403-3cd95780-f427-11ea-9757-7b39f0eebf7d.JPG)
On the PTR client and the Shadowlands Beta, when this addon is enabled it briefly flashes the following on startup:

"You do not have permission to perform that function"

Tested as the only addon loaded.  It still seems to work, but this only appears on load that I've seen, or when the UI is reloaded, as with the /console reloadui.

**Comment by funkydude** [comment]
This error seems to appear no matter what and doesn't seem related to this addon. Thanks anyway.
